### ISSUE TITLE
xVhdFile - with network share not working

### ISSUE THREAD

**Issue by dominikheeb** [PowerShell/xHyper-V#127]
I tried to use xVhdFile to copy some installation media onto the vhdx file.
There is no error message but the files are missing

The source is a network share.
My configuration:
MSFT_xFileDirectory {
                            SourcePath = $Node.InstallationMediaFolder
                            DestinationPath = "InstallationMedia"
                            Ensure = "Present"
                            Recurse  = $true
                            Type = "Directory"
                            Force = $true
                        }

My Node Data:

@{
    AllNodes = @(      
      @{
        NodeName = '*'
        InstallationMediaFolder = "\\networksource\share\AutomatedInstallation\InstallationMedia"
      }
    )
  }

**Comment by iainbrighton** [comment]
@dominikheeb When copying files over the network you will need the credentials to authenticaate. The LCM runs under the LOCALSYSTEM context and won't have access to the network share - unless you've granted the computer account access.

Can you try granting the computer's account access to the network share? If you're using WMF 5.0 (or later) you can also try using the `PSDSCRunAsCredential` built-in parameter.

**Comment by dominikheeb** [comment]
Thank you for the answer.
The issue was due to a network problem and is solved now.
The Permission i had already added.
