### ISSUE TITLE
xVMHost: Add support for enabling/disabling Live Migration

### ISSUE THREAD

**Issue by janegilring** [PowerShell/xHyper-V#155]
#### Details of the scenario you tried and the problem that is occurring

Currently it is not possible to enable and disable Live Migration of virtual machines by leveraging the xVMHost DSC module. This is a common feature to enable, and would be beneficial having as an option in this module.

#### Verbose logs showing the problem

Live Migration of Virtual Machines is disabled by default for Hyper-V. This can be shown by checking the VirtualMachineMigrationEnabled property in the output of Get-VMHost:

PS C:\> Get-VMHost

Name     LogicalProcessorCount MemoryCapacity(M) VirtualMachineMigrationEnabled
----     --------------------- ----------------- ------------------------------
HV01  32                    262074,203125     False

#### Suggested solution to the issue

Add a VirtualMachineMigrationEnabled property to xVMHost, which can leverage the following cmdlets to perform the logic:
Get-VMHost
Enable-VMMigration
Disable-VMMigration

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
xVMHost HyperVHostSettings
    {

        IsSingleInstance    = 'Yes'
       #VirtualMachineMigrationEnabled  <-- The property currently missing (in version 3.12.0.0) , which this issue suggests adding
        VirtualMachineMigrationAuthenticationType = 'Kerberos'
        VirtualMachineMigrationPerformanceOption = 'Compression'
        MaximumStorageMigrations = '2'
        MaximumVirtualMachineMigrations = '4'
        UseAnyNetworkForMigration = $true
        DependsOn = @('[WindowsFeature]Hyper-V','[WindowsFeature]Hyper-V-PowerShell')

    }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2485.amd64fre.rs1_release.180827-1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.12.0.0

**Comment by johlju** [comment]
Thanks @janegilring! Sounds like a good enhancement to the resource. Labeling as help wanted so that anyone in the community can pick this up.
