### ISSUE TITLE
xVMHyperV: RestartIfNeeded not setting properly

### ISSUE THREAD

**Issue by jaykeblakk** [PowerShell/xHyper-V#159]
Building a VM and then setting the property RestartIfNeeded to $true does nothing, and it remains false.

Here is an example of the code:

		xVHD TestHD
		{
			Ensure = "Present"
			Name = "Test.vhdx"
			Path = "F:\Test\Virtual Hard Disks"
			Generation = "vhdx"
			MaximumSizeBytes = 256GB
		}

		xVMHyperV TestVM
		{
			Ensure = "Present"
			DependsOn = "[xVHD]TestHD"
			Name = "Test"
			VhdPath = "F:\Test\Virtual Hard Disks\Test.vhdx"
			SwitchName = "Internal Switch 2"
			Path = "F:\Test"
			Generation = 2
			StartupMemory = 16GB
			ProcessorCount = '8'
			RestartIfNeeded = $true
			State = 'Running'
		}

		xVMScsiController TestSCSI
		{
			Ensure = "Present"
			VMName = "Test"
			DependsOn = "[xVHD]TestHD"
			ControllerNumber = 0
		}

The vhdx is created properly and throws no errors. The VM is then created without throwing any errors. However, when the DSC runs to create the SCSI controller, I receive the following output:

VERBOSE: [TESTENVIRONMENT]: LCM:  [ Start  Test     ]  [[xVMScsiController]TestSCSI]
VERBOSE: [TESTENVIRONMENT]:                            [[xVMScsiController]TestSCSI] Found controller '0' attached to VM 'Test'.
VERBOSE: [TESTENVIRONMENT]:                            [[xVMScsiController]TestSCSI] Comparing 'RestartIfNeeded'; expected '', actual 'False'.
VERBOSE: [TESTENVIRONMENT]:                            [[xVMScsiController]TestSCSI] Comparing 'ControllerNumber'; expected '0', actual '0'.
VERBOSE: [TESTENVIRONMENT]:                            [[xVMScsiController]TestSCSI] Comparing 'VMName'; expected 'Test', actual 'Test'.
VERBOSE: [TESTENVIRONMENT]:                            [[xVMScsiController]TestSCSI] Comparing 'Ensure'; expected 'Present', actual 'Present'.
VERBOSE: [TESTENVIRONMENT]: LCM:  [ End    Test     ]  [[xVMScsiController]TestSCSI]  in 0.1560 seconds.
VERBOSE: [TESTENVIRONMENT]: LCM:  [ Start  Set      ]  [[xVMScsiController]TestSCSI]
VERBOSE: [TESTENVIRONMENT]: LCM:  [ End    Set      ]  [[xVMScsiController]TestSCSI]  in 0.0630 seconds.
PowerShell DSC resource MSFT_xVMScsiController  failed to execute Set-TargetResource functionality with error message: Cannot update a running VM unless 'RestartIfNeeded' is set to true.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : testenvironment

**Comment by bgelens** [comment]
Hi @jaykeblakk. Not sure if you still need assistance with this but if you do, ```RestartIfNeeded``` needs to be set on the xVMScsiController resource.

```powershell
xVMScsiController TestSCSI
{
	Ensure = "Present"
	VMName = "Test"
	DependsOn = "[xVHD]TestHD"
	ControllerNumber = 0
        RestartIfNeeded = $true
}
```
