### ISSUE TITLE
Test should "return" True/False

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/xHyper-V#16]
Currently, Test-TR "retrunes" True/False instead of returning True/False. No time to fix right now...

**Comment by KarolKaczmarek** [comment]
What resource you are talking about here?

**Comment by kort3x** [comment]
He talks about MSFT_xVhdFileDirectory.psm1 in Line 263.
It says:         Write-Verbose "Test retruned $result"
Should say:  Write-Verbose "Test returned $result"
