### ISSUE TITLE
$letterDrive contains leading tab stop

### ISSUE THREAD

**Issue by kort3x** [PowerShell/xHyper-V#20]
I had issues with the variable $letterDriver in MSFT_xVhdFileDirectory.psm1

When trying to copy an unattend.xml into a vhdx, DSC would fail with an DriveNotFound error.
I finaly realized that $letterDrive did not contain for example "E:\" but also a leading tab stop, and of course drive "[tab stop]E:\" cannot be found.

I fixed it with the substring method to get rid of the tab stop.
$letterDrive = $letterDrive.Substring($letterDrive.Length - 3,3)

**Comment by kort3x** [comment]
Issue still exists for me. Nobody?

**Comment by BerheAbrha** [comment]
I don't see where the tab is coming in the drive letter. But in any case we may call trim to on the $letterDrive.Trim() to eliminate white spaces. @kort3x  do you want to fix/ test it in the repro machine that you have  and send a pull request for this.

**Comment by kort3x** [comment]
Sure. I will test the trim-method.

**Comment by kort3x** [comment]
Trim does not work. $letterdrive still contains "  E:\"
I will go back to $letterDrive = $letterDrive.Substring($letterDrive.Length - 3,3), which seems to do the trick.

**Comment by jeepasaurus** [comment]
I ran into this problem as well... See my pull request: 
https://github.com/PowerShell/xHyper-V/pull/38

$mountedDrive.DriveLetter returns a CharArray... I used -join to fix it. Not sure if that is the best way to go about it. But it fixed it for me.

**Comment by kwirkykat** [comment]
Fixed in #38
