### ISSUE TITLE
Secure Boot

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#30]
When a Generation 2 VM is created, Secure Boot is automatically enabled. Some software (Citrix) will not install when this is enabled. Therefore, a Secure Boot resource would be extremely handy to have at our disposal!

**Comment by iainbrighton** [comment]
I see three available options:
 1. Default to secure boot OFF for Gen 2 VMs and add a new parameter to enable. Some linux distrubutions/appliances also have issues with secure boot.
 2. Default to secure boot ON for Gen2 VMs and add a new paramater to disable (safest).
 3. Add an additional/separate resource to enable/disable secure boot.

My preferred option would be number 1, but does anyone else have a view?

**Comment by HemantMahawar** [comment]
I would prefer to go with 2nd option as it is more secure option (https://technet.microsoft.com/en-us/library/dn486875.aspx) and is the default in Windows (https://technet.microsoft.com/en-us/library/dn282285.aspx).

**Comment by iainbrighton** [comment]
Thanks Hemant - I'll get to work ;) Iain
