### ISSUE TITLE
Add multiple vNIC support to xVMHyperV

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#33]
I now need to have the functionality to assign a VM to multiple vSwitches, e.g. provide multi-homed VMs. The real question is should this be provided by the xVMHyperV resource or by another completely new/separate resource? This is a similar question to #31 which relates to multiple VHDs.

If it was part of the xVMHyperV resource we could change the SwitchName and MACAddress properties to string[]. This would maintain backwards compatibility whilst permitting the assignment of multiple virtual NICs.

If we were going to implement a new resource, it would have to ignore the first NIC in a VM as that would be managed by the xVMHyperV resource :(. This would no doubt lead to confusion.

If we were starting from scratch I would propose splitting the xVMHyperV functionality into distinct xVM, xVMNic and xVMDisk resources. However, we are where we are! Does anyone have a view/thoughts on the way in which we should proceed?

**Comment by HemantMahawar** [comment]
I agree with your proposal of making MACAddress and SwitchName as string[]. The only additional ask would be to add an example highlighting this new functionality and updating the description of these parameters.
