### ISSUE TITLE
Wrong value for 'Generation' field in Examples

### ISSUE THREAD

**Issue by zjalali** [PowerShell/xHyper-V#36]
Install xHyper-V module version 3.2.0.0 from PSGallery. In some examples (e.g. Sample_xVMHyperV_Complete) we have:
# Ensures a VM with all the properties

xVMHyperV NewVM
{
    Ensure          = 'Present'
    Name            = $VMName
    VhdPath         = $VhdPath
    SwitchName      = $SwitchName
    State           = $State
    Path            = $Path
    Generation      = $VhdPath.Split('.')[-1]
    StartupMemory   = $StartupMemory
    MinimumMemory   = $MinimumMemory
    MaximumMemory   = $MaximumMemory
    ProcessorCount  = $ProcessorCount
    MACAddress      = $MACAddress
    RestartIfNeeded = $true
    WaitForIP       = $WaitForIP 
    DependsOn       = '[WindowsFeature]HyperV'
}

But the schema has:

[ClassVersion("1.0.0"), FriendlyName("xVMHyperV")]
class MSFT_xVMHyperV : OMI_BaseResource
{
 ...
    [Write, Description("Virtual machine generation")] Uint32 Generation;
...
};

I think previous versions had something similar to schema for xVHD:

[ClassVersion("1.0.0"), FriendlyName("xVHD")]
class MSFT_xVHD : OMI_BaseResource
{
...
    [Write, Description("Virtual disk format - Vhd or Vhdx"), ValueMap{"Vhd","Vhdx"}, Values{"Vhd","Vhdx"}] String Generation;
...
};

**Comment by iainbrighton** [comment]
The VM generation was changed to an integer a little while ago (v3.0.0.0?). It looks like I missed this one in the readme.md.

Good catch - I'll update it!

**Comment by zjalali** [comment]
Thanks @iainbrighton .

**Comment by ericjaystevens** [comment]
While fixed in the readme the correction still needs to be made in Examples\ as the original poster mentioned. 

1. Sample_xVMHyperV_Complete.ps1 
1. Sample_xVMHyperV_DynamicMemory.ps1 
1. Sample_xVMHyperV_Simple.ps1

**Comment by ITGuyOU** [comment]
#70
