### ISSUE TITLE
[Discussion] Resource granularity

### ISSUE THREAD

**Issue by rchaganti** [PowerShell/xHyper-V#47]
I see that there are multiple requests here and also new changes that went it to the last release which actually pack multiple resource configurations into a single resource. For example, multiple VM NIC support in the VM resource. So, my question is, shouldn't these configurations be individual resources. For example, VM creates just a VM. You can use the VHD resource and add that VHD configuration as a dependency in VM. Similarly, you can use VMNetworkAdapter and VMNetworkAdapterVLAN resources to add the relevant configuration to VMs. This, IMHO, provides granularity and gives better control. Instead of bloating VM resource with everything we need, shouldn't we take this path.

I am sure this is a not an easy change looking at the way how these resources are authored. But, what are your thoughts? I come from a school of thought that DSC resources should be as granular as possible and I have been following this in all the resource module I had written so far. 

In fact, I have resources that create VMNetworkAdapter (VM or Host OS), assign VLANs to them, and even inject IP addresses into VMs. I love this level of control.

**Comment by DexterPOSH** [comment]
:+1:  to the Resource granularity.

I am trying to automate creation of a NatVM which has multiple nics (few of these should have VLanID tagged) but this is not possible with current implementation of xVMHyperV DSC resource (or did I miss something? ).

**Comment by iainbrighton** [comment]
Here's my 2p

@rchaganti I am most certainly all-in for individual resources, see #31 and #43. Whether that's an individual resource for every setting, I'm not entirely convinced yet. Regardless, there is a strong desire to ___not break the existing xVMHyperV implementation___. That means leaving the ability to create vNICs as part of xVMHyperV :-1:.

@DexterPOSH Correct - this functionality is not currently available. There is outstanding request #44  for setting VLAN IDs, but I've left it alone pending the outcome of discussions on a new `xVMNetworkAdapter` resource. I see no point trying to shoehorn VLAN IDs into `xVMHyperV`.

My preference would be to leave xVMHyperV alone and deprecate it. Start afresh with:
* xVM
 * Creates a VM without any disks or NICs.
 * Manage CPU, memory and SecureBoot configuration settings etc.
* xVMDisk
 * Manages and attaches VHD(s) assigned to a VM.
 * The xVHD resource would still be used for creating VHD(X)s.
* xVMNetworkAdapter
 * Manages and attaches NIC(s), MAC(s) and VLAN ID(s) etc.

Heck - after all that lot - we could even turn xHyperVM into a composite resource mimicking the existing behaviour and no one would ever notice!

**Comment by rchaganti** [comment]
:+1: 

I have my own VM implementation. Let me make that public once I polish it completely. I personally don't like the way xHyperVVM is implemented.

**Comment by DexterPOSH** [comment]
@iainbrighton I agree with the whole idea of start afresh.

**Comment by TheBlackMini** [comment]
This discussion looks like it reached a conclusion yet nothing happened? (Kinda trying to bump this)
@rchaganti How goes your own VM modules?

**Comment by rchaganti** [comment]
@TheBlackMini there were review comments I started addressing and then went off-track. Will resume it soon and push a PR again.
