### ISSUE TITLE
xVMSwitch test fails if BandwidthReservationMode is not specified

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#48]
In the latest release, if the `BandwidthReservationMode` is not specified, the Test method always fails. This appears to be due to the Get method returning the value, which by default (on a Win 10 host for me at least) actually happens to be 'Absolute' and not 'NA'.
```powershell
PS C:\> Get-TargetResource -Name Internet -Type Internal -Verbose

Name                           Value
----                           -----
AllowManagementOS              True
BandwidthReservationMode       Absolute
Id                             71d7a9fb-a501-41a4-861d-199175b95bd8
Name                           Internet
Type                           Internal
Ensure                         Present
NetAdapterInterfaceDescription
NetAdapterName

PS C:\> Test-TargetResource -Name Internet -Type Internal -Verbose
VERBOSE: Checking if Switch Internet is Present ...
VERBOSE: Switch Internet is Present
VERBOSE: Checking if Switch Internet has correct BandwidthReservationMode ...
False
```
This might cause a few problems in production. I'll add a test and update the code...

**Comment by TheBlackMini** [comment]
So, a little more light on this issue...
Windows 10 / Server 2016 default value is 'Absolute' for 'MinimumBandwidthMode'
Windows 8 & 8.1 / Server 2012 & R2 default value is 'Weight' for 'MinimumBandwidthMode'
