### ISSUE TITLE
xVMHyperV Cannot validate argument on parameter 'Path'

### ISSUE THREAD

**Issue by tanerg** [PowerShell/xHyper-V#52]
I get the following error:

Test-TargetResource on MSFT_xVMHyperV DSC resource. FullyQualifiedErrorId is ParameterArgumentValidationError,Get-VhdHierarchy. Error Message is Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again..

After some investigation I think the test "$vmVhdPath.ParentPath -ne [String]::Empty" on line 612 in the function Get-VhdHierarchy is not sufficient. For some reason the property ParentPath is null in my case and passes the test so it throws an error on line 615.

**Comment by iainbrighton** [comment]
@tanerg Does changing the code to `while(-not [String]::IsNullOrEmpty($vmVhdPath.ParentPath))` fix your issue?

**Comment by TigerScript** [comment]
Hi Ian, 
That code change resolved my problem with this resource, although I am calling it through the puppet dsc resources. Thanks!

Ps. Hope you are well.

Tony.

**Comment by tanerg** [comment]
Hi Ian,

It also fixes my problem. Thx.

**Comment by iainbrighton** [comment]
@tanerg @TigerScript Cool - I'll get a PR in for this change
PS - I'm good thanks Tony! Hope you're well too :smiley:
