### ISSUE TITLE
Enforced VM Power State

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#6]
The current implement of the xVMHyper-V resource enforces that a VM is in a particular power state. If no state is specified then it's powered off!

I think that this is incorrect behaviour as it will turn off VMs __unless__ you explicitly state you want VMs running __all__ the time. In a lab/dev/test (or maybe even a production) environment, you might want to ensure that VMs are provisioned in a particular way, but managing the power state is not always desirable (pun intended!).

I think this should be the behaviour:

* If the configuration document specifies a State of 'Off', 'Running' or 'Paused' then this should be enforced.
* If the configuration document does not specify a State, then no change to the VM should be made.

**Comment by vors** [comment]
Agree
