### ISSUE TITLE
Add Support for Managing SCSI/IDE Controllers

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xHyper-V#64]
This would make use of the `*-VMScsiController` and `*-VMIdeController` cmdlets. This is not a commonly used function, but may be required.

**Comment by Haelters** [comment]
I'm working on VMScsiController in the context of #66. 
This will allow: 
* ensuring Controllers are present/absent

However ,the VMIdeController seems useless, since it is not possible to add IDE controllers.

**Comment by iainbrighton** [comment]
I think you'll need a Gen 1 VM to be able to add an IDE controller?

**Comment by Haelters** [comment]
@iainbrighton Unless I'm mistaking, it's not possible to add/remove IDE controllers from a Gen I VM. There are always two of them.

**Comment by iainbrighton** [comment]
@Haelters I've just tried this and yes - you are correct! Not what I expected, but it does seem that a `xVMIdeController` resource is superfluous to our requirements!

**Comment by johlju** [comment]
@PlagueHO There is as xVMScsiController resource. Does this satisfy this issue? Or do we need a xVMIdeController as well?

**Comment by iainbrighton** [comment]
@johlju @PlagueHO I think this can be closed? There is now a xVMScsiController resource and there is no need for a xVMIdeController resource:

* There is always two IDE controllers created in a Gen1 VM and you can't remove them
* You cannot add an IDE controller to a Gen2 VM

**Comment by johlju** [comment]
Closing as per previous comment. If this was closed in error, then please reopen or comment.
