### ISSUE TITLE
Incorporate changes from fork

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xHyper-V#66]
There is a fork of this module that has interesting additions.
[https://github.com/robwi/xHyper-V](https://github.com/robwi/xHyper-V)

HELP WANTED

If anyone would like to review the changes, determine which would benefit the community, and drive them as a new PR, that would be a great project.  It is lacking tests and documentation, so this is not a small undertaking.

**Comment by Haelters** [comment]
I don't mind looking into this. However, It would be my first contribution and any guidance and feedback will be very much appreciated.

**Comment by PlagueHO** [comment]
Hi @Haelters - it would be awesome to have the help if you want to take this on! All help is gratefully accepted and appreciated :smile:

I'm happy to help you with the technical stuff of getting the resources in line to merge into the upstream repo.

There are a few logistical questions that need to be answered though:
1. Which resources do we want to merge from @robwi 's repo?
2. Which features can we copy across? 
3. How do we go about taking these "chosen" resources, modifying them to meet guidelines and adding unit/integration tests and then submitting the PR to the @PowerShellTeam repo?

Looking at the two repos:
- PowerShell/xVHD has similar function to robwi/xVHD
- PowerShell/xVMHyperV has similar function robwi/xVM (there are some additional boolean flags here).
- robwi/xVMProcessorMaximum - just contains a single parameter - couldn't this just be added to xVMHyperV?
- robwi/xVMAddDisk - this is the most useful one that I think could be migrated. @rchaganti - do you have anything in your xHyper-V that you're planning on moving across that would conflict with this one?

Given the above I'd suggest the answers to the logistical questions might be:
1. xVMAddDisk.
2. some features of xVM
3. I'm not sure, but possibly:
- @Haelters forks Powershell/xHyper-V
- @Haelters Manually copy files from robwi/xHyper-V that we want to include into fork.
- @Haelters makes changes to fork to meet guidelines, adds unit & integration tests.
- @Haelters submits PR to PowerShell/xHyper-V

Sorry about the long response, but this sort of "merge" isn't something I've done before. So I'm sure others may have much better ideas than I!

**Comment by rchaganti** [comment]
I have a bunch of new resources in my cHyper-V module. I will be merging changes to xVMSwitch to add SET functionality very soon.

I will add other new resources as well.
- xVMNetworkAdapterVLAN
- xVMNetworkAdapterSettings
- xVMNetworkAdapterMapping
- xVMIPAddress
- xWaitForVMGuestIntegration
- xSimpleVM (very simple VM with no strings! :-))
- xVMFile (over PowerShell Direct)
- xVMCommand (over PowerShell Direct)

I will have these with HQRM guidance complete.

**Comment by Haelters** [comment]
I'll start with the xVMAddDisk, as this might be an easy one to get started and learn about all the do/don'ts. 

I've already forked the Powershell/xHyper-V and will copy/generate the files required for xVMAddDisk and adapt to guidelines (I will have to study them) and generate the unit and integration tests. I hope that at that point, some of you will be able to review what I've done and then we can launch the PR to PowerShell/xHyper-V.

**Comment by Haelters** [comment]
@rchaganti I've also been thinking about the xVMFile, but in the context of xVhdFile. 

The scenario is that I use DSC to ensure certain Vhdx exist on a host and make sure certain files are included in the vhdx. This works perfectly the first time as the VHDX is not yet in use. However, subsequent launches generate an error on the xVhdFile because the VHDX is in use by the VM.

What I intended to do was to modify xVhdFile to handle two cases transparently for the user:
- The Vhdx is not in use: simply take the approach that is currently implemented: i.e. mount the vhd and copy.
- The Vhdx is currently in use (in a running VM): there the approach would be to simply copy it over using PowerShell Direct. 

A parameter could be used to determine if a file may be injected in a disk on a running VM (this would trigger the requirement for credentials).

Is this a good approach to avoid having two resources that in essence do the same? (if I should ask this somewhere else, please let me know - still learning)

**Comment by Haelters** [comment]
Could someone take a look at the extra resources I've created:
https://github.com/PowerShell/xHyper-V/compare/dev...Haelters:Issue-66

As you can see, I've created two extra resources:
- xVMHardDiskDrive: allowing to add/remove/change drives to a VM
- xVMScsiController: allowing to add/remove SCSI controllers (See #64)

At first I started with quite some complexity in it (e.g. when adding a hard disk drive on a non existent controller, it was automatically added). However, I think that this complexity should be handled in the DSC configuration and not in the resource. I've also set it up in a way that adding additional features should be very easy (e.g. MaximumIOPS).

If you agree with the proposal, I'll continue with the other options and resources (e.g. xVMProcessor). It should go a lot faster now :-))

The only issue I'm currently having some issues with, are the tests. I find it quite useless as we may not use the actual Hyper-V cmdlets. I've started mocking them, but creating mocked functions that fully mimic the Get-VMHardDiskDrive is quite a heavy job. I'll continue looking into it.

@kwirkykat: could you place this one 'in progress' please?

**Comment by iainbrighton** [comment]
@Haelters I am keen to get the xVMScsiController and xVMHardDiskDrive resources merged into this repository. Is there anything that you need to progress this PR? Presumably you are using the fork in your repository for internal purposes?

**Comment by ScottArbeit** [comment]
@Haelters, I'm also keen to see these new resources merged into the repo. Thank you for doing the work... I'll the new resources as soon as they're in place.

**Comment by ChrisLGardner** [comment]
@Haelters If you're having problems with writing tests and mocking Hyper-V cmdlets then have a look at [Stub Commands](https://github.com/indented-automation/Indented.StubCommand) as a way of handling that.

**Comment by iainbrighton** [comment]
@ChrisLGardner Ha - I was looking at that Pester internals to generate that functionality for one of my upcoming presentations! I shall now add a link to your repo instead 😃.

@Haelters @ScottArbeit I've started working on the change in [this fork](https://github.com/iainbrighton/xHyper-V/tree/Issue66) and will add unit test etc. assuming @Haelters is OK with this?

**Comment by iainbrighton** [comment]
@Haelters Are you OK for me to take over your work [in this fork](https://github.com/iainbrighton/xHyper-V/tree/Issue66)? If you would rather continue to develop it, then that's OK by me too 😃!

**Comment by Haelters** [comment]
Go ahead. Currently I don't have the time.

Best regards
