### ISSUE TITLE
Property EnableGuestService in DSC resource xHyper-V throws error on non English Windows version

### ISSUE THREAD

**Issue by GeriOnline** [PowerShell/xHyper-V#73]
Hello,
I'm trying to create VMs on a non-English (German) Windows version with xHyper-V while setting the VM property _EnableGuestService_. But an error _InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMIntegrationService_ is thrown. A look into the source of MSFT_xVMHyperV.psm1 shows why: The name of this integration service is a hard coded string for English Windows versions (_'Guest Service Interface'_). In non English Windows version this service has other names (e.g. in German Windows 10 Pro '_Gastdienstschnittstelle_'). Any plans to make this language neutral? Would be very helpful when working in mixed language environments.
Gerhard

**Comment by PlagueHO** [comment]
Thanks for raising the issue @GeriOnline 

I ran into this issue when creating LabBuilder. You can see the way it was resolved [here](https://github.com/PlagueHO/LabBuilder/blob/dev/LabBuilder/lib/private/vm.ps1#L1114). Essentially we'll need to look up the "culture neutral" name of the integration service using the GUID assigned to it and use that to translate it.

I don't have time to do this at the moment, but if no one else gets to it in the next month I'll try and get to it.

**Comment by GeriOnline** [comment]
I just saw that this issue is also described in issue #76 and it seems that a solution is coming. So I will close this one and wait till the pending pull request is committed.
Thank you for your tip with LabBuilder. It helped me to fix the issue temporarily for a current project.
