### ISSUE TITLE
xVMHyperV - EnableGuestService does not work localized OS

### ISSUE THREAD

**Issue by vrdse** [PowerShell/xHyper-V#76]
The EnableGuestService option in xVMHyperV doesn't work in localized OS (non-EN), as the name 'Guest Service Interface' does not exist. 

MSFT_xVMHyper.psm1 uses *-VMIntegrationService Cmdlets with the -Name Parameter 
(e.g. Line 94         
EnableGuestService = ($vmobj | Get-VMIntegrationService -Name 'Guest Service Interface').Enabled). 

Unfortunately Microsoft localized the integration service names, like 'Gastdienstschnittstelle' in german, instead of 'Gues Service Interface'. Therefore checking and setting the Guest Service status fails on non-EN systems.

In my opinion, there are two ways to identify the Guest Service without its name.
1. TypeName: Every guest service has its own object type. Guest Service Interface is [Microsoft.HyperV.PowerShell.GuestServiceInterfaceComponent]
2. Id: Every guest service has an unique Id. In the object the id looks like 'Microsoft:<VMGUID>\6C09BB55-D683-4DA0-8931-C9BF705F6480'. This could be matched with a Regex like  "Microsoft:[0-9A-Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}\\6C09BB55-D683-4DA0-8931-C9BF705F6480"

**Comment by vrdse** [comment]
I tried to fix the issue here: https://github.com/vrdse/xHyper-V/blob/dev/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1

However, the Pester test now fails and I'm not shure why or how to fix. Any help is appreciated.

**Comment by bgelens** [comment]
Reopened to track #100 This is a release blocker until merged.
