### ISSUE TITLE
Support for Nested Virtualization?

### ISSUE THREAD

**Issue by GeriOnline** [PowerShell/xHyper-V#81]
With Windows Server 2016 (and also Win10 since some time) it's possible to configure a VM so it can act as a Hyper-V host. It would be a nice enhancement of the xHyper-V resource if I'm able to define this during creation of the VM either by a new 'NestedVirtualization' property or (probably the better way) by setting the associated properties like _MAC spoofing_ and _ExposeVirtualizationExtensions_ separately.

**Comment by iainbrighton** [comment]
@GeriOnline The MAC spoofing setting will need to be added to the xVMNetAdapter resource. I also need to implement DeviceNaming so will look to do that, but we should open a new/separate issue for this.

As for enabling nested virtualization, this will require a new xVMProcessor resource. Here's a proposed schema:
```powershell
[ClassVersion("1.0.0.0"), FriendlyName("xVMProcessor")]
class MSFT_xVMProcessor : OMI_BaseResource
{
    [Key, Description("Specifies the name of the virtual machine on which the processor is to be configured.")] String VMName;
    [Write, Description("Specifies whether to enable host resource protection.")] Boolean EnableHostResourceProtection;
    [Write, Description("")] Boolean ExposeVirtualizationExtensions;
    [Write, Description("")] Uint64 HwThreadCountPerCore;
    [Write, Description("Specifies the maximum percentage of resources available to the virtual machine processor to be configured. Allowed values range from 0 to 100.")] Uint64 Maximum;
    [Write, Description("Specifies the maximum number of processors per NUMA node to be configured for the virtual machine.")] Uint32 MaximumCountPerNumaNode;
    [Write, Description("Specifies the maximum number of sockets per NUMA node to be configured for the virtual machine.")] Uint32 MaximumCountPerNumaSocket;
    [Write, Description("Specifies the priority for allocating the physical computer's processing power to this virtual machine relative to others. Allowed values range from 1 to 10000.")] Uint32 RelativeWeight;
    [Write, Description("Specifies the percentage of processor resources to be reserved for this virtual machine. Allowed values range from 0 to 100.")] Uint64 Reserve;
    [Write, Description("Specifies the name of the processor resource pool to be used.")] String ResourcePoolName;
    [Write, Description("Specifies whether the virtual processors features are to be limited for compatibility when migrating the virtual machine to another host.")] Boolean CompatibilityForMigrationEnabled;
    [Write, Description("Specifies whether the virtual processor’s features are to be limited for compatibility with older operating systems.")] Boolean CompatibilityForOlderOperatingSystemsEnabled;
};
```
I have left the processor count out as this could conflict with the xVMHyperV resource's processor count. Is everyone OK with this schema before I get cracking?

**Comment by GeriOnline** [comment]
@iainbrighton Yes it's a great idea to pack all these processor properties into a separate resource with the proposed schema.

Concerning Device Naming and MAC Address Spoofing: There's already a DSC resource [cVMNetworkAdapterSettings](https://github.com/rchaganti/DSCResources/tree/master/cHyper-V/DSCResources/cVMNetworkAdapterSettings) published by @rchaganti which implements these properties (and a lot more). I used this resource in the past without any problem.

Of course if you wish a separate issue for this I will open one.

**Comment by iainbrighton** [comment]
I'll pick up with this as no one has claimed it 😉.

**Comment by iainbrighton** [comment]
@PlagueHO if you would kindly review this at some point in the near future - it's not urgent - it would be appreciated 😄.
