### ISSUE TITLE
xVMDvdDrive hard-coded 'ADCSTest' VMName

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#85]
In [xVMDvdDrive](https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMDvdDrive/MSFT_xVMDvdDrive.psm1#L395-L396) the `VMName` parameter is hard-coded to `ADCSTest`. This makes it kind of hard to attach an ISO to any other machine 😜.

**Comment by PlagueHO** [comment]
My bad :cry: Will submit a PR.

**Comment by PlagueHO** [comment]
Submitted a PR to resolve this (with new regression tests):
https://github.com/PowerShell/xHyper-V/pull/86
