### ISSUE TITLE
xHyper-V does not set Fixed Memory in client Hyper-V

### ISSUE THREAD

**Issue by GeriOnline** [PowerShell/xHyper-V#89]
It's not possible to create a VM with xHyper-V in a client Hyper-V environment like Win10. Reason: In client Hyper-V 'dynamic memory' is set by default whereas in server environments this defaults to 'fixed memory'. So you cannot create a VM with fixed memory in client Hyper-V with the xHyperV resource even when minimum and maximum memory is not specified. How to solve this? 

Maybe in the Set-TargetDevice function when creating the VM you should set the 'fixed memory' parameter  to true by default (currently nothing is done with this); clearing this and setting 'dynamic memory' only when minimum or maximum memory is specified.

But in addition how can I switch between these settings with a DSC configuration for an already created VM?

**Comment by GeriOnline** [comment]
Any news on this topic?

**Comment by bgelens** [comment]
I haven't come around to look at all the issues yet. Since I became maintainer for this module my top priority was / is to handle the outstanding PRs first. (just a little excuse from my side :wink:

I understand the issue, this would require some additional logic and the use of ```Set-VMMemory -DynamicMemoryEnabled $false``` in case of client SKU and only StartupMemory is defined. I think the check for client SKU can even be omitted as it won't impact the VM created on the server SKU. Am I missing / overlooking something? @iainbrighton @PlagueHO

Right now I don't have time to contribute this myself so assigning labels in the hope somebody can beat me to it (will do this eventually if nobody else picks it up)

**Comment by iainbrighton** [comment]
Whilst apparently not quite the same, I always just set the startup, minimum and maximum memory to the same values, e.g. all 4GB etc to "fix" it.

**Comment by GeriOnline** [comment]
@bgelens I think you're right to omit the client SKU check. But as far as I understand the code in the .psm1 file it's not enough to use `Set-VMMemory`. Especially in the `Set-TargetResource` function where you are gathering the memory properties for a call to `Set-VM` we should set both properties `-StaticMemory`  and `-DynamicMemory` accordingly.
If you do not have time for these changes at the moment, I offer to do this. However this would be my first try to contribute something to a public repository. What have I to do?
- Fork current xHyper-V dev branch
- Modify and test the code
- Send a pull request back to you

Is this the right way?

@iainbrighton Your tip with setting the startup, minimum and maximum memory to the same values seems to work (I tried it with a nested Hyper-V VM and Hyper-V can be started). However the VM property `DynamicMemoryEnabled` of course remains `$true`. So this might be a workaround but not really fix the issue.

**Comment by bgelens** [comment]
That would be awesome @GeriOnline! Go for it 👍 Please see the [Contribution Guideline](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#fixing-an-issue), [Style Guideline](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md) to get started.

**Comment by GeriOnline** [comment]
Meanwhile I signed the CLA. I plan to change the code in the following manner:

- If neither _MinimumMemory_ nor _MaximumMemory_ is specified dynamic memory will be disabled.
- If _MinimumMemory_ and _MaximumMemory_ are both specified and have the same value as _StartupMemory_ then dynamic memory will also be disabled. This would be the suggestion from @iainbrighton .

Would this approach be okay?

An additional way would be to introduce a new optional property _DynamicMemoryEnabled_ with which you can explicitly set the corresponding VM property to _$true_ or _$false_. If not specified, the above method would be applied. However I would prefer solely the first way because the interface of the DSC resource remains unchanged.

I would appreciate a quick feedback. Thank you.
