### ISSUE TITLE
add xVMNetAdapterVlan

### ISSUE THREAD

**Issue by omiossec** [PowerShell/xHyper-V#90]
Since we have a xVMNetAdapter module it will be nice to have a xVMNetAdapterVlan to configure vmnetadapter.
I am working on It but I may not have many time.
This new ressource will change the vmnetadapter (by name) vlan properties (Acces or Trunk)
I plan to use class based ressource instead of mof 
:

**Comment by iainbrighton** [comment]
@omiossec There is a [cVMNetworkAdapterVlan resource](https://github.com/rchaganti/DSCResources/tree/master/cHyper-V/DSCResources/cVMNetworkAdapterVlan) from @rchaganti that includes this functionality. Hopefully, it'll be merged into this repo at some point, until then you can always use Ravi's resource.

**Comment by rchaganti** [comment]
I need some help with tests. Anyone?

**Comment by BarnumD** [comment]
Also interested in seeing this built in to this module.  I use this via upstream puppet modules.

**Comment by rchaganti** [comment]
I have been porting all my Hyper-V related DSC resources into https://github.com/rchaganti/hypervdsc. Do check that.

**Comment by BarnumD** [comment]
Thanks @rchaganti, but since I'm using an upstream module via puppet (puppetlabs-dsc) I'm locked into what's in the official repos.

**Comment by aromano2** [comment]
resolved with #161
