### ISSUE TITLE
xVMHyperV - does not permit VM creation with StartupMemory greater the 17GB

### ISSUE THREAD

**Issue by MnrGreg** [PowerShell/xHyper-V#93]
One is currently not able to provision a VM guest with StartupMemory of greater than 17GB. While Dynamic Memory can get around this, from a performance point of view StartupMemory is preferred. Most cloud offerings support up to 64GB. Recommendation is to increase to xHyper-v to 64GB.

Error when trying to set to 20GB:

> PowerShell DSC resource MSFT_xVMHyperV  failed to execute Test-TargetResource functionality with error message: Cannot validate argument on parameter 'StartupMemory'. The 21474836480 argument is greater than the maximum allowed range of 18184404992. Supply an argument that is less than or equal to 18184404992 and then try the command again.

xHyper-V / DSCResources / MSFT_xVMHyperV / [MSFT_xVMHyperV.psm1](https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1)

```
# Startup RAM for the VM 
[ValidateRange(32MB,17342MB)] 
[UInt64]$StartupMemory, 
```

**Comment by bgelens** [comment]
I think all the memory properties need to be reviewed. Gen 1 VM max memory is 1TB but Gen 2 VM is 12 TB according to [2016 scalability guide](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-for-hyper-v-scalability-in-windows-server-2016)

The resource current maximum is 1048576MB which is the 1TB limit for Gen1.

I don't know where / when the validateset on Startup, Minimum and Maximum where established but I think they need to be adjusted to the most modern limits.

Tagging @iainbrighton in case he has some insights on these validateset and if they should be maintained for some reason?
